<?php

namespace DoctrineORMModule\Proxy\__CG__\Base\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \Base\Model\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUserType()
    {
        $this->__load();
        return parent::getUserType();
    }

    public function setUserType($userType)
    {
        $this->__load();
        return parent::setUserType($userType);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getMiddleName()
    {
        $this->__load();
        return parent::getMiddleName();
    }

    public function setMiddleName($middleName)
    {
        $this->__load();
        return parent::setMiddleName($middleName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getAlternateName()
    {
        $this->__load();
        return parent::getAlternateName();
    }

    public function setAlternateName($alternameName)
    {
        $this->__load();
        return parent::setAlternateName($alternameName);
    }

    public function getShowAlternateName()
    {
        $this->__load();
        return parent::getShowAlternateName();
    }

    public function setShowAlternateName($showAlternateName)
    {
        $this->__load();
        return parent::setShowAlternateName($showAlternateName);
    }

    public function getDisplayName()
    {
        $this->__load();
        return parent::getDisplayName();
    }

    public function setDisplayName($displayName = NULL)
    {
        $this->__load();
        return parent::setDisplayName($displayName);
    }

    public function getDisplayNameOrder()
    {
        $this->__load();
        return parent::getDisplayNameOrder();
    }

    public function setDisplayNameOrder($displayNameOrder)
    {
        $this->__load();
        return parent::setDisplayNameOrder($displayNameOrder);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username = NULL)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getHasSilhouette()
    {
        $this->__load();
        return parent::getHasSilhouette();
    }

    public function setHasSilhouette($hasSilhouette)
    {
        $this->__load();
        return parent::setHasSilhouette($hasSilhouette);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getEmailPreset()
    {
        $this->__load();
        return parent::getEmailPreset();
    }

    public function setEmailPreset($emailPreset)
    {
        $this->__load();
        return parent::setEmailPreset($emailPreset);
    }

    public function getNotificationSetting()
    {
        $this->__load();
        return parent::getNotificationSetting();
    }

    public function setNotificationSetting($notificationSetting)
    {
        $this->__load();
        return parent::setNotificationSetting($notificationSetting);
    }

    public function getTagNotifications()
    {
        $this->__load();
        return parent::getTagNotifications();
    }

    public function setTagNotifications($tagNotifications)
    {
        $this->__load();
        return parent::setTagNotifications($tagNotifications);
    }

    public function getAccounts()
    {
        $this->__load();
        return parent::getAccounts();
    }

    public function setAccounts(\Doctrine\Common\Collections\ArrayCollection $accounts)
    {
        $this->__load();
        return parent::setAccounts($accounts);
    }

    public function getFriendRequests()
    {
        $this->__load();
        return parent::getFriendRequests();
    }

    public function setFriendRequests(\Doctrine\Common\Collections\ArrayCollection $receivedRequests)
    {
        $this->__load();
        return parent::setFriendRequests($receivedRequests);
    }

    public function getFollowers()
    {
        $this->__load();
        return parent::getFollowers();
    }

    public function setFollowers(\Doctrine\Common\Collections\ArrayCollection $followers)
    {
        $this->__load();
        return parent::setFollowers($followers);
    }

    public function getFollowing()
    {
        $this->__load();
        return parent::getFollowing();
    }

    public function setFollowing(\Doctrine\Common\Collections\ArrayCollection $following)
    {
        $this->__load();
        return parent::setFollowing($following);
    }

    public function getLikes()
    {
        $this->__load();
        return parent::getLikes();
    }

    public function setLikes(\Doctrine\Common\Collections\ArrayCollection $likes)
    {
        $this->__load();
        return parent::setLikes($likes);
    }

    public function getPhotoTaags()
    {
        $this->__load();
        return parent::getPhotoTaags();
    }

    public function setPhotoTags(\Doctrine\Common\Collections\ArrayCollection $photoTags)
    {
        $this->__load();
        return parent::setPhotoTags($photoTags);
    }

    public function getSentFriendRequests()
    {
        $this->__load();
        return parent::getSentFriendRequests();
    }

    public function setSentFriendRequests(\Doctrine\Common\Collections\ArrayCollection $sentRequests)
    {
        $this->__load();
        return parent::setSentFriendRequests($sentRequests);
    }

    public function getTravelLogAdmins()
    {
        $this->__load();
        return parent::getTravelLogAdmins();
    }

    public function setTravelLogAdmins(\Doctrine\Common\Collections\ArrayCollection $travelLogAdmins)
    {
        $this->__load();
        return parent::setTravelLogAdmins($travelLogAdmins);
    }

    public function update(\Application\StdLib\Observable $observable)
    {
        $this->__load();
        return parent::update($observable);
    }

    public function addAccount(\Base\Model\TravelLogAdmin $account)
    {
        $this->__load();
        return parent::addAccount($account);
    }

    public function addFriendRequest(\Base\Model\FriendRequest $friendRequest)
    {
        $this->__load();
        return parent::addFriendRequest($friendRequest);
    }

    public function addFollower(\Base\Model\User $follower)
    {
        $this->__load();
        return parent::addFollower($follower);
    }

    public function addFollowing(\Base\Model\User $following)
    {
        $this->__load();
        return parent::addFollowing($following);
    }

    public function addLike(\Base\Model\Like $like)
    {
        $this->__load();
        return parent::addLike($like);
    }

    public function addPhoto(\Base\Model\Photo $photo)
    {
        $this->__load();
        return parent::addPhoto($photo);
    }

    public function addSentFriendRequest(\Base\Model\FriendRequest $friendRequest)
    {
        $this->__load();
        return parent::addSentFriendRequest($friendRequest);
    }

    public function addTravelLogAdmin(\Base\Model\TravelLogAdmin $travelLogAdmin)
    {
        $this->__load();
        return parent::addTravelLogAdmin($travelLogAdmin);
    }

    public function addTravelLog(\Base\Model\TravelLog $travelLog)
    {
        $this->__load();
        return parent::addTravelLog($travelLog);
    }

    public function countFriends()
    {
        $this->__load();
        return parent::countFriends();
    }

    public function countMutualConnections(\Base\Model\User $user)
    {
        $this->__load();
        return parent::countMutualConnections($user);
    }

    public function countRequests()
    {
        $this->__load();
        return parent::countRequests();
    }

    public function countActiveRequests()
    {
        $this->__load();
        return parent::countActiveRequests();
    }

    public function equals(\Application\StdLib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getProfileAlbum()
    {
        $this->__load();
        return parent::getProfileAlbum();
    }

    public function getAllFriends()
    {
        $this->__load();
        return parent::getAllFriends();
    }

    public function getHomeStream()
    {
        $this->__load();
        return parent::getHomeStream();
    }

    public function getRequests()
    {
        $this->__load();
        return parent::getRequests();
    }

    public function getTagged()
    {
        $this->__load();
        return parent::getTagged();
    }

    public function getTravelLog($name = NULL)
    {
        $this->__load();
        return parent::getTravelLog($name);
    }

    public function getTravelLogs()
    {
        $this->__load();
        return parent::getTravelLogs();
    }

    public function initDisplayName()
    {
        $this->__load();
        return parent::initDisplayName();
    }

    public function isConnectedTo(\Base\Model\User $user = NULL)
    {
        $this->__load();
        return parent::isConnectedTo($user);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getPicture()
    {
        $this->__load();
        return parent::getPicture();
    }

    public function setPicture(\Base\Model\Photo $picture)
    {
        $this->__load();
        return parent::setPicture($picture);
    }

    public function getCoverPicture()
    {
        $this->__load();
        return parent::getCoverPicture();
    }

    public function setCoverPicture(\Base\Model\Photo $coverPicture)
    {
        $this->__load();
        return parent::setCoverPicture($coverPicture);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAlbums()
    {
        $this->__load();
        return parent::getAlbums();
    }

    public function setAlbums(\Doctrine\Common\Collections\ArrayCollection $albums)
    {
        $this->__load();
        return parent::setAlbums($albums);
    }

    public function getFeed()
    {
        $this->__load();
        return parent::getFeed();
    }

    public function setFeed(\Doctrine\Common\Collections\ArrayCollection $feed)
    {
        $this->__load();
        return parent::setFeed($feed);
    }

    public function getInterests()
    {
        $this->__load();
        return parent::getInterests();
    }

    public function setInterests(\Doctrine\Common\Collections\ArrayCollection $interests)
    {
        $this->__load();
        return parent::setInterests($interests);
    }

    public function getLinks()
    {
        $this->__load();
        return parent::getLinks();
    }

    public function setLinks(\Doctrine\Common\Collections\ArrayCollection $links)
    {
        $this->__load();
        return parent::setLinks($links);
    }

    public function getNotifications()
    {
        $this->__load();
        return parent::getNotifications();
    }

    public function setNotifications(\Doctrine\Common\Collections\ArrayCollection $notifications)
    {
        $this->__load();
        return parent::setNotifications($notifications);
    }

    public function setPhotos(\Doctrine\Common\Collections\ArrayCollection $photos)
    {
        $this->__load();
        return parent::setPhotos($photos);
    }

    public function getStatuses()
    {
        $this->__load();
        return parent::getStatuses();
    }

    public function setStatuses(\Doctrine\Common\Collections\ArrayCollection $statuses)
    {
        $this->__load();
        return parent::setStatuses($statuses);
    }

    public function addAlbum(\Base\Model\Album $album)
    {
        $this->__load();
        return parent::addAlbum($album);
    }

    public function addFeed(\Base\Model\Status $status)
    {
        $this->__load();
        return parent::addFeed($status);
    }

    public function addInterest(\Base\Model\Interest $interest)
    {
        $this->__load();
        return parent::addInterest($interest);
    }

    public function addLink(\Base\Model\Link $link)
    {
        $this->__load();
        return parent::addLink($link);
    }

    public function addNotification(\Base\Model\Notification $notification)
    {
        $this->__load();
        return parent::addNotification($notification);
    }

    public function addStatus(\Base\Model\Status $status)
    {
        $this->__load();
        return parent::addStatus($status);
    }

    public function countNotifications()
    {
        $this->__load();
        return parent::countNotifications();
    }

    public function getAlbum($name = NULL)
    {
        $this->__load();
        return parent::getAlbum($name);
    }

    public function getAlbumById($id = 0)
    {
        $this->__load();
        return parent::getAlbumById($id);
    }

    public function getMessages()
    {
        $this->__load();
        return parent::getMessages();
    }

    public function getPhotos()
    {
        $this->__load();
        return parent::getPhotos();
    }

    public function getPosts()
    {
        $this->__load();
        return parent::getPosts();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'creationDate', 'lastUpdateDate', 'picture', 'coverPicture', 'albums', 'feed', 'interests', 'links', 'notifications', 'photos', 'statuses', 'userType', 'firstName', 'middleName', 'lastName', 'alternateName', 'showAlternateName', 'displayName', 'displayNameOrder', 'email', 'password', 'hasSilhouette', 'gender', 'emailPreset', 'notificationSetting', 'tagNotifications', 'accounts', 'friendRequests', 'followers', 'following', 'likes', 'photoTags', 'sentFriendRequests', 'travelLogAdmins');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}