<?php

namespace DoctrineORMModule\Proxy\__CG__\Base\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TravelLog extends \Base\Model\TravelLog implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getAbout()
    {
        $this->__load();
        return parent::getAbout();
    }

    public function setAbout($about)
    {
        $this->__load();
        return parent::setAbout($about);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getGeneralInfo()
    {
        $this->__load();
        return parent::getGeneralInfo();
    }

    public function setGeneralInfo($generalInfo)
    {
        $this->__load();
        return parent::setGeneralInfo($generalInfo);
    }

    public function getLink()
    {
        $this->__load();
        return parent::getLink();
    }

    public function setLink($link)
    {
        $this->__load();
        return parent::setLink($link);
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setCategory($category)
    {
        $this->__load();
        return parent::setCategory($category);
    }

    public function getIsPublished()
    {
        $this->__load();
        return parent::getIsPublished();
    }

    public function setIsPublished($isPublished)
    {
        $this->__load();
        return parent::setIsPublished($isPublished);
    }

    public function getCanPost()
    {
        $this->__load();
        return parent::getCanPost();
    }

    public function setCanPost($canPost)
    {
        $this->__load();
        return parent::setCanPost($canPost);
    }

    public function getNumLikes()
    {
        $this->__load();
        return parent::getNumLikes();
    }

    public function setNumLikes($numLikes)
    {
        $this->__load();
        return parent::setNumLikes($numLikes);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function setLocation($location)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function geteNumCheckins()
    {
        $this->__load();
        return parent::geteNumCheckins();
    }

    public function setNumCheckins($numCheckins)
    {
        $this->__load();
        return parent::setNumCheckins($numCheckins);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getAdministrators()
    {
        $this->__load();
        return parent::getAdministrators();
    }

    public function setAdministrators(\Doctrine\Common\Collections\ArrayCollection $administrators)
    {
        $this->__load();
        return parent::setAdministrators($administrators);
    }

    public function getDisplayName()
    {
        $this->__load();
        return parent::getDisplayName();
    }

    public function addAdministrator(\Base\Model\TravelLogAdmin $travelLogAdmin)
    {
        $this->__load();
        return parent::addAdministrator($travelLogAdmin);
    }

    public function equals(\Application\StdLib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getPicture()
    {
        $this->__load();
        return parent::getPicture();
    }

    public function setPicture(\Base\Model\Photo $picture)
    {
        $this->__load();
        return parent::setPicture($picture);
    }

    public function getCoverPicture()
    {
        $this->__load();
        return parent::getCoverPicture();
    }

    public function setCoverPicture(\Base\Model\Photo $coverPicture)
    {
        $this->__load();
        return parent::setCoverPicture($coverPicture);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAlbums()
    {
        $this->__load();
        return parent::getAlbums();
    }

    public function setAlbums(\Doctrine\Common\Collections\ArrayCollection $albums)
    {
        $this->__load();
        return parent::setAlbums($albums);
    }

    public function getFeed()
    {
        $this->__load();
        return parent::getFeed();
    }

    public function setFeed(\Doctrine\Common\Collections\ArrayCollection $feed)
    {
        $this->__load();
        return parent::setFeed($feed);
    }

    public function getInterests()
    {
        $this->__load();
        return parent::getInterests();
    }

    public function setInterests(\Doctrine\Common\Collections\ArrayCollection $interests)
    {
        $this->__load();
        return parent::setInterests($interests);
    }

    public function getLinks()
    {
        $this->__load();
        return parent::getLinks();
    }

    public function setLinks(\Doctrine\Common\Collections\ArrayCollection $links)
    {
        $this->__load();
        return parent::setLinks($links);
    }

    public function getNotifications()
    {
        $this->__load();
        return parent::getNotifications();
    }

    public function setNotifications(\Doctrine\Common\Collections\ArrayCollection $notifications)
    {
        $this->__load();
        return parent::setNotifications($notifications);
    }

    public function setPhotos(\Doctrine\Common\Collections\ArrayCollection $photos)
    {
        $this->__load();
        return parent::setPhotos($photos);
    }

    public function getStatuses()
    {
        $this->__load();
        return parent::getStatuses();
    }

    public function setStatuses(\Doctrine\Common\Collections\ArrayCollection $statuses)
    {
        $this->__load();
        return parent::setStatuses($statuses);
    }

    public function addAlbum(\Base\Model\Album $album)
    {
        $this->__load();
        return parent::addAlbum($album);
    }

    public function addFeed(\Base\Model\Status $status)
    {
        $this->__load();
        return parent::addFeed($status);
    }

    public function addInterest(\Base\Model\Interest $interest)
    {
        $this->__load();
        return parent::addInterest($interest);
    }

    public function addLink(\Base\Model\Link $link)
    {
        $this->__load();
        return parent::addLink($link);
    }

    public function addNotification(\Base\Model\Notification $notification)
    {
        $this->__load();
        return parent::addNotification($notification);
    }

    public function addStatus(\Base\Model\Status $status)
    {
        $this->__load();
        return parent::addStatus($status);
    }

    public function countNotifications()
    {
        $this->__load();
        return parent::countNotifications();
    }

    public function getAlbum($name = NULL)
    {
        $this->__load();
        return parent::getAlbum($name);
    }

    public function getAlbumById($id = 0)
    {
        $this->__load();
        return parent::getAlbumById($id);
    }

    public function getMessages()
    {
        $this->__load();
        return parent::getMessages();
    }

    public function getPhotos()
    {
        $this->__load();
        return parent::getPhotos();
    }

    public function getPosts()
    {
        $this->__load();
        return parent::getPosts();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'creationDate', 'lastUpdateDate', 'picture', 'coverPicture', 'albums', 'feed', 'interests', 'links', 'notifications', 'photos', 'statuses', 'name', 'about', 'description', 'generalInfo', 'link', 'category', 'isPublished', 'canPost', 'numLikes', 'location', 'phone', 'numCheckins', 'website', 'administrators');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}