<?php

namespace DoctrineORMModule\Proxy\__CG__\Base\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Photo extends \Base\Model\Photo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getAlbum()
    {
        $this->__load();
        return parent::getAlbum();
    }

    public function setAlbum(\Base\Model\Album $album)
    {
        $this->__load();
        return parent::setAlbum($album);
    }

    public function getFrom()
    {
        $this->__load();
        return parent::getFrom();
    }

    public function setFrom(\Base\Model\Traveloti $from)
    {
        $this->__load();
        return parent::setFrom($from);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getMessage()
    {
        $this->__load();
        return parent::getMessage();
    }

    public function getPlace()
    {
        $this->__load();
        return parent::getPlace();
    }

    public function setPlace($place)
    {
        $this->__load();
        return parent::setPlace($place);
    }

    public function getIcon()
    {
        $this->__load();
        return parent::getIcon();
    }

    public function setIcon($icon)
    {
        $this->__load();
        return parent::setIcon($icon);
    }

    public function getPicture()
    {
        $this->__load();
        return parent::getPicture();
    }

    public function setPicture($picture)
    {
        $this->__load();
        return parent::setPicture($picture);
    }

    public function getSource()
    {
        $this->__load();
        return parent::getSource();
    }

    public function setSource($source)
    {
        $this->__load();
        return parent::setSource($source);
    }

    public function getSrcHeight()
    {
        $this->__load();
        return parent::getSrcHeight();
    }

    public function setSrcHeight($srcHeight)
    {
        $this->__load();
        return parent::setSrcHeight($srcHeight);
    }

    public function getSrcWidth()
    {
        $this->__load();
        return parent::getSrcWidth();
    }

    public function setSrcWidth($srcWidth)
    {
        $this->__load();
        return parent::setSrcWidth($srcWidth);
    }

    public function getLink()
    {
        $this->__load();
        return parent::getLink();
    }

    public function setLink($link)
    {
        $this->__load();
        return parent::setLink($link);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getVisibility()
    {
        $this->__load();
        return parent::getVisibility();
    }

    public function setVisibility($visibility)
    {
        $this->__load();
        return parent::setVisibility($visibility);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function setComments(\Doctrine\Common\Collections\ArrayCollection $comments)
    {
        $this->__load();
        return parent::setComments($comments);
    }

    public function getLikes()
    {
        $this->__load();
        return parent::getLikes();
    }

    public function setLikes(\Doctrine\Common\Collections\ArrayCollection $likes)
    {
        $this->__load();
        return parent::setLikes($likes);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function setTags(\Doctrine\Common\Collections\ArrayCollection $tags)
    {
        $this->__load();
        return parent::setTags($tags);
    }

    public function getImageResource()
    {
        $this->__load();
        return parent::getImageResource();
    }

    public function getObservers()
    {
        $this->__load();
        return parent::getObservers();
    }

    public function setObservers(array $observers = array (
))
    {
        $this->__load();
        return parent::setObservers($observers);
    }

    public function addComment(\Base\Model\Comment $comment)
    {
        $this->__load();
        return parent::addComment($comment);
    }

    public function addLike(\Base\Model\Like $like)
    {
        $this->__load();
        return parent::addLike($like);
    }

    public function addTag(\Base\Model\Tag $tag)
    {
        $this->__load();
        return parent::addTag($tag);
    }

    public function attach(\Application\StdLib\Observer $observer)
    {
        $this->__load();
        return parent::attach($observer);
    }

    public function compareTo(\Base\Model\Photo $o)
    {
        $this->__load();
        return parent::compareTo($o);
    }

    public function countLikes()
    {
        $this->__load();
        return parent::countLikes();
    }

    public function crop($left, $top, $width, $height)
    {
        $this->__load();
        return parent::crop($left, $top, $width, $height);
    }

    public function equals(\Application\StdLib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getHeight()
    {
        $this->__load();
        return parent::getHeight();
    }

    public function getNotifierText(\Base\Model\Traveloti $sender)
    {
        $this->__load();
        return parent::getNotifierText($sender);
    }

    public function getWidth()
    {
        $this->__load();
        return parent::getWidth();
    }

    public function notify()
    {
        $this->__load();
        return parent::notify();
    }

    public function place(\Base\Model\Photo $image, $left = 0, $top = 0, $opacity = 100)
    {
        $this->__load();
        return parent::place($image, $left, $top, $opacity);
    }

    public function resize($width, $height, $flags = 0)
    {
        $this->__load();
        return parent::resize($width, $height, $flags);
    }

    public function save($filename = NULL, $quality = NULL, $type = NULL)
    {
        $this->__load();
        return parent::save($filename, $quality, $type);
    }

    public function send($type = 2, $quality = NULL)
    {
        $this->__load();
        return parent::send($type, $quality);
    }

    public function sharpen()
    {
        $this->__load();
        return parent::sharpen();
    }

    public function detach(\Application\StdLib\Observer $observer)
    {
        $this->__load();
        return parent::detach($observer);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'place', 'icon', 'picture', 'source', 'srcHeight', 'srcWidth', 'link', 'position', 'visibility', 'type', 'creationDate', 'lastUpdateDate', 'album', 'from', 'comments', 'likes', 'tags');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}