<?php
/* @var $rf Zend\Form\Form */

$title = "Sign Up for Traveloti";
$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('/css/traveloti/logged-out.css'));
$this->headLink()->appendStylesheet($this->basePath('/css/traveloti/login.css'));

$rf = $this->registerForm;
$rf->prepare();

// Set form attributes
$rf->setAttributes(array(
	'action' => 'register',
	'method' => 'post',
	'name' => 'reg',
));
?>
<div id="pagelet-blue-bar">
	<div id="blue-bar-holder">
		<div id="blue-bar">
			<div class="loggedout-menubar-container">
				<div class="container_16">
					<div class="loggedout-menubar">
						<div class="grid_7 tr-logo-loggedout-wrapper">
							<a href="#"> <i class="tr-logo-loggedout"></i>
							</a>
						</div>
						<div class="grid_9 login-container">
							<table
								cellspacing="0"
								cellpadding="0">
								<tr>
									<td class="login-label"><label>Sign In With:</label></td>
								</tr>
								<tr>
									<td><?php
									$fb_href = $this->url('scn-social-auth-user/login/provider', array('provider' => 'facebook'));
									$tw_href = $this->url('scn-social-auth-user/login/provider', array('provider' => 'twitter'));
									$fs_href = $this->url('scn-social-auth-user/login/provider', array('provider' => 'foursquare'));
									?> <a
										class="social-btn-link fb-login-icon"
										href="<?php echo $fb_href; ?>"></a> <a
										class="social-btn-link tw-login-icon"
										href="<?php echo $tw_href; ?>"></a> <a
										class="social-btn-link fs-login-icon"
										href="<?php echo $fs_href; ?>"></a>
									</td>
								</tr>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div
	id="content"
	class="clearfix">
	<div class="fullpage-container">
		<div id="main-container">
			<div class="content-topper">
				<div class="content-topper-text-container">
					<h1 class="mbs _3m8 _6n _6s _6v">Sign Up</h1>
					<h2 class="mbl _3m7 _6o _6t _mf">Join Traveloti to share your
						travels and learn valuable tips and advice from friends and other
						travelers. It's free and always will be.</h2>
				</div>
				<div class="window-shade">
					<div class="simple-registration-form">
						<div class="simple-registration-container">
							<div id="reg-box">
								<?php if ($rf->getMessages()) : ?>
								<div class="login-error-box box-red">
									<?php foreach ($rf->getMessages() as $message) : ?>
									<div class="login-error-msg">
										<?php foreach ($message as $msg) : ?>
										<p>
											<?php print_r($msg); ?>
										</p>
										<?php endforeach; ?>
									</div>
									<?php endforeach; ?>
								</div>
								<?php endif; ?>
								<?php echo $this->form()->openTag($rf); ?>
								<?php echo $this->formHidden($rf->get("creationDate")); ?>
								<div class="clearfix short-fields">
									<div class="mrm lfloat">
										<?php echo $this->formElement($rf->get("firstName")); ?>
										<div class="form-error">
											<?php echo $this->formElementErrors($rf->get("password")); ?>
										</div>
									</div>
									<div class="mbm rfloat">
										<?php echo $this->formElement($rf->get("lastName")); ?>
										<div class="form-error">
											<?php echo $this->formElementErrors($rf->get("password")); ?>
										</div>
									</div>
								</div>
								<div class="mbm">
									<?php echo $this->formElement($rf->get("email")); ?>
									<div class="form-error">
										<?php echo $this->formElementErrors($rf->get("password")); ?>
									</div>
								</div>
								<div class="mbm">
									<?php echo $this->formElement($rf->get("password")); ?>
									<div class="form-error">
										<?php echo $this->formElementErrors($rf->get("password")); ?>
									</div>
								</div>
								<div class="mbm">
									<?php echo $this->formElement($rf->get("passwordVerify")); ?>
									<div class="form-error">
										<?php echo $this->formElementErrors($rf->get("password")); ?>
									</div>
								</div>

								<div class="mtm mbs callout-label">Member Type:</div>
								<div class="clearfix field-container">
									<?php echo $this->formRow($rf->get("userType")); ?>
									<div class="form-error">
										<?php echo $this->formElementErrors($rf->get("password")); ?>
									</div>
								</div>

								<div class="mtl mbm">
									<?php echo $this->formRow($rf->get("gender")); ?>
									<div class="form-error">
										<?php echo $this->formElementErrors($rf->get("password")); ?>
									</div>
								</div>
								<div class="reg-btn clearfix">
									<?php echo $this->formElement($rf->get("submit_btn")); ?>
								</div>
								<?php echo $this->form()->closeTag(); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
