<div id="main-container">
	<div id="left-column-container">
		<div id="left-column">
			<?php echo $this->pageletWelcomeBox ?>
			<?php echo $this->pageletNavigation ?>
		</div>
	</div>
	<div
		id="content-column"
		class="clearfix has-right-column home-wider-content has-expanded-composer news-feed-composer">
		<div id="right-column"></div>
		<div id="content-area">
			<?php echo $this->pageletComposer; ?>
			<?php echo $this->pageletHomeStream; ?>
		</div>
	</div>
</div>
