<?php
$headTitle = $this->zfcUserIdentity()->getDisplayName() . ' | Traveloti';
$this->headTitle($headTitle);
?>
<body class="timeline-layout trx">
	<div>
		<?php echo $this->pageletLeaderboard; ?>
		<div
			id="global-container"
			class="contextual-layout-parent">
			<div
				id="content"
				class="tr-content clearfix">
				<div>
					<div id="main-container">
						<div id="left-column-container">
							<div
								id="left-column"
								style="display: none;"></div>
						</div>
						<div
							id="content-column"
							class="clearfix has-right-column">
							<div id="right-column"></div>
							<div id="content-area">
								<?php echo $this->content; ?>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php echo $this->footer; ?>
		</div>
	</div>
	<?php
	if(null != $this->overlay) {
		echo $this->overlay;
	}
	?>
</body>