<?php

$title = 'Delete Country';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete country
    '<?php echo $this->escapeHtml($country->getName()); ?>' with ISO code
    '<?php echo $this->escapeHtml($country->getIsoCode()); ?>'?
</p>
<?php
$url = $this->url('country', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $country->getId(); ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>