<div id="page-footer">
	<div
		id="footer-container"
		class="clearfix">
		<div class="copyright">Traveloti &copy; 2012</div>
		<div class="disclaimer">This is a developmental website only and not
			to be confused with an actual functioning production website.
			Traveloti is not responsible for designs, features and claims made or
			inferred from this test website. All elements on this developmental
			website are subject to change.</div>
	</div>
</div>
