<!-- begin xmpp-logger pagelet -->
<div id="control-wrapper" class="hidden-element">
	<div id="control">
		<p>
			<input
				id="chat-clear"
				type="button"
				value="Clear"> <input
				id="logCheck"
				type="checkbox"
				checked="checked"> <label for="logCheck">Logging</label> <input
				id="chat-test"
				type="button"
				value="Test">
		</p>
		<p>
			<input
				id="connect"
				type="button"
				value="Connect"> <input
				id="disconnect"
				type="button"
				value="Disconnect">
		</p>
	</div>
	<div id="logger-log"></div>
</div>
<!-- end xmpp-logger pagelet -->
