<?php
return array(
    'template_path_stack' => array(
        'traveloti' => __DIR__ . '/view',
    ),
	'template_map' => array(
		'base/ajax/index'					=> __DIR__ . '/view/base/ajax/index.phtml',
		'base/base/chat_roster'			=> __DIR__ . '/view/base/base/chat_roster.phtml',
		'base/base/composer'				=> __DIR__ . '/view/base/base/composer.phtml',
		'base/base/dock'					=> __DIR__ . '/view/base/base/dock.phtml',
		'base/base/new_dock'				=> __DIR__ . '/view/base/base/new_dock.phtml',
		'base/base/footer'					=> __DIR__ . '/view/base/base/footer.phtml',
		'base/base/full_page_layout'		=> __DIR__ . '/view/base/base/full_page_layout.phtml',
		'base/base/home_stream'				=> __DIR__ . '/view/base/base/home_stream.phtml',
		'base/base/index'					=> __DIR__ . '/view/base/base/index.phtml',
		'base/base/index_timeline'			=> __DIR__ . '/view/base/base/index_timeline.phtml',
		'base/base/leaderboard'				=> __DIR__ . '/view/base/base/leaderboard.phtml',
		'base/base/left_column_layout'		=> __DIR__ . '/view/base/base/left_column_layout.phtml',
		'base/base/navigation'				=> __DIR__ . '/view/base/base/navigation.phtml',
		'base/base/notification'			=> __DIR__ . '/view/base/base/notification.phtml',
		'base/base/notifications_jewel'		=> __DIR__ . '/view/base/base/notifications_jewel.phtml',
		'base/base/photo_stream'			=> __DIR__ . '/view/base/base/photo_stream.phtml',
		'base/base/photo-stream-overlay'	=> __DIR__ . '/view/base/base/photo-stream-overlay.phtml',
		'base/base/requests_jewel'			=> __DIR__ . '/view/base/base/requests_jewel.phtml',
		'base/base/timeline'				=> __DIR__ . '/view/base/base/timeline.phtml',
		'base/base/timeline_navigation'		=> __DIR__ . '/view/base/base/timeline_navigation.phtml',
		'base/base/travel_log_create'		=> __DIR__ . '/view/base/base/travel_log_create.phtml',
		'base/base/welcome_box'				=> __DIR__ . '/view/base/base/welcome_box.phtml',
		'base/base/xmpp_logger'				=> __DIR__ . '/view/base/base/xmpp_logger.phtml',
		'base/find-travelotis/browser'		=> __DIR__ . '/view/base/find-travelotis/browser.phtml',
		'base/find-travelotis/search'		=> __DIR__ . '/view/base/find-travelotis/search.phtml',
		'base/settings/general'				=> __DIR__ . '/view/base/settings/general.phtml',
		'base/settings/index'				=> __DIR__ . '/view/base/settings/index.phtml',
		'base/settings/log_admin'			=> __DIR__ . '/view/base/settings/log_administrator.phtml',
		'base/settings/log_general'			=> __DIR__ . '/view/base/settings/log_general.phtml',
		'base/settings/log_profile'			=> __DIR__ . '/view/base/settings/log_profile.phtml',
		'base/settings/profile'				=> __DIR__ . '/view/base/settings/profile.phtml',
		'base/timeline/connections'			=> __DIR__ . '/view/base/timeline/connections.phtml',
		'base/timeline/photos'				=> __DIR__ . '/view/base/timeline/photos.phtml',
		'layout/base_layout'				=> __DIR__ . '/view/layout/base_layout.phtml',
	),
);