<?php

$title = 'Delete Location';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete location
    '<?php echo $this->escapeHtml($location->getCountry()); ?>' with postal code
    '<?php echo $this->escapeHtml($location->getPostalCode()); ?>'?
</p>
<?php
$url = $this->url('location', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $location->getId(); ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>