<?php
$title = 'Edit Location';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'location',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('country'));
echo $this->formRow($form->get('region'));
echo $this->formRow($form->get('city'));
echo $this->formRow($form->get('postal_code'));
echo $this->formRow($form->get('metro_code'));
echo $this->formRow($form->get('area_code'));
echo $this->formRow($form->get('latitude'));
echo $this->formRow($form->get('longitude'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>